name: Build iOS App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install, Add iOS, and Build
        run: |
          npm install
          npm install @capacitor/ios --save
          rm -rf ios
          npx cap add ios
          npx cap sync ios
          cd ios/App
          pod install
          xcodebuild -workspace App.xcworkspace -scheme App -sdk iphonesimulator -configuration Debug build
